### ISSUE TITLE
O botão de enter não funciona!

### ISSUE THREAD

**Issue by iamthatgiulia** [alinerhanny/entendendo-o-autismo#1]
Olá, tudo bem?

Estava dando uma olhada no seu projeto e gostei muito! Porém percebi que o seu botão de enter não funciona como descrito no código abaixo (o escrito no seu repositório):

inputPesquisa.addEventListener("keypress", function(event) {
  if (event.key === "Enter") {
    pesquisar();
  }
});

Acredito que o problema é que nenhum valor é inserido como parâmetro na função pesquisar(), que é uma função que pede por um! 

Tente apenas colocar o valor inputPesquisa.value como parâmetro e tudo deve funcionar. Ficaria assim:

inputPesquisa.addEventListener("keypress", function(event) {
  if (event.key === "Enter") {
    pesquisar(inputPesquisa.value);
  }
});

Só para deixar claro, o inputPesquisa.value é o valor inserido pelo usuário na sua barra de pesquisas.
Espero que eu tenha ajudado!

**Comment by alinerhanny** [comment]
Oii, Problema resolvido. Obrigada!!
